"""
Sanction letter generator.

Called by the Decision Engine when the user accepts an offer.
Produces a PDF using ReportLab, uploads it to Supabase Storage, and writes a
SanctionLetter row pointing at the upload (status: pending_admin_review).
"""

from __future__ import annotations

import io
import secrets
from datetime import datetime, timezone

from fastapi import HTTPException, status
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle,
)
from sqlalchemy.orm import Session

from app.database.models import (
    AgentDecision, LoanApplication, LoanOffer, SanctionLetter, User,
)
from app.services.storage_service import StorageService
from app.utils.logger import logger


SAARTHI_PURPLE = colors.HexColor("#6C63FF")


class SanctionWriter:
    @staticmethod
    async def issue(
        db: Session, application: LoanApplication, offer: LoanOffer, user: User
    ) -> SanctionLetter:
        # Idempotency — if one already exists, return it
        existing = (
            db.query(SanctionLetter)
            .filter(SanctionLetter.application_id == application.id)
            .first()
        )
        if existing:
            logger.info(f"[Sanction] reusing existing letter for app={application.id}")
            return existing

        ref_no = _make_ref()
        pdf_bytes = _render_pdf(application, offer, user, ref_no)

        # Upload PDF — same Supabase bucket as KYC media for now.
        path = f"sanctions/{application.id}/{ref_no}.pdf"
        full_path = await StorageService.upload(path, pdf_bytes, "application/pdf")

        letter = SanctionLetter(
            application_id=application.id,
            ref_no=ref_no,
            pdf_url=full_path,
            status="pending_admin_review",
        )
        db.add(letter)
        db.add(AgentDecision(
            application_id=application.id,
            agent_name="sanction_writer",
            decision="letter_generated",
            reasoning=f"Sanction letter {ref_no} created for offer #{offer.id}.",
            llm_trace={
                "ref_no": ref_no,
                "offer_id": offer.id,
                "pdf_size_bytes": len(pdf_bytes),
            },
        ))
        application.status = "sanctioned"
        db.commit()
        db.refresh(letter)
        logger.info(f"[Sanction] issued {ref_no} for app={application.id}")
        return letter


# ─── Helpers ──────────────────────────────────────────────────────────────────
def _make_ref() -> str:
    """Reference number like SAR-2026-A7K9F2."""
    year = datetime.now(timezone.utc).year
    suffix = secrets.token_hex(3).upper()
    return f"SAR-{year}-{suffix}"


def _render_pdf(
    application: LoanApplication,
    offer: LoanOffer,
    user: User,
    ref_no: str,
) -> bytes:
    """Lay out a 1-page sanction letter and return its PDF bytes."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=20 * mm, rightMargin=20 * mm,
        topMargin=18 * mm, bottomMargin=18 * mm,
    )
    styles = getSampleStyleSheet()
    h1 = styles["Title"]
    h1.textColor = SAARTHI_PURPLE
    body = styles["BodyText"]
    small = styles["Italic"]

    story = []
    story.append(Paragraph("Saarthi Finance — Sanction Letter (Draft)", h1))
    story.append(Spacer(1, 4 * mm))
    story.append(Paragraph(
        f"Reference: <b>{ref_no}</b><br/>"
        f"Issued: {datetime.now(timezone.utc).strftime('%d %b %Y, %H:%M UTC')}<br/>"
        f"Status: <b>Pending admin review</b>",
        body,
    ))
    story.append(Spacer(1, 8 * mm))

    story.append(Paragraph(f"Dear {user.full_name},", body))
    story.append(Spacer(1, 2 * mm))
    story.append(Paragraph(
        "We are pleased to offer you the following loan, subject to final verification "
        "and administrative approval. This letter is auto-generated by Saarthi's "
        "Decision Intelligence Engine.",
        body,
    ))
    story.append(Spacer(1, 6 * mm))

    rows = [
        ["Applicant",        user.full_name],
        ["Email",            user.email],
        ["Phone",            user.phone or "—"],
        ["Application ID",   f"#{application.id}"],
        ["Loan amount",      f"₹ {offer.amount:,.0f}"],
        ["Interest rate",    f"{offer.interest_rate:.2f}% p.a."],
        ["Tenure",           f"{offer.tenure_months} months"],
        ["Monthly EMI",      f"₹ {offer.emi:,.0f}"],
        ["Total payable",    f"₹ {offer.emi * offer.tenure_months:,.0f}"],
        ["Negotiated offer", "Yes" if offer.is_negotiated else "No"],
    ]
    table = Table(rows, colWidths=[55 * mm, 100 * mm])
    table.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (0, -1), colors.HexColor("#F0F0F8")),
        ("TEXTCOLOR",     (0, 0), (0, -1), colors.HexColor("#444444")),
        ("FONTNAME",      (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME",      (1, 0), (1, -1), "Helvetica"),
        ("FONTSIZE",      (0, 0), (-1, -1), 10),
        ("ROWBACKGROUNDS",(0, 0), (-1, -1), [colors.white, colors.HexColor("#FAFAFC")]),
        ("BOX",           (0, 0), (-1, -1), 0.4, colors.HexColor("#E5E5EF")),
        ("INNERGRID",     (0, 0), (-1, -1), 0.3, colors.HexColor("#EEEEF3")),
        ("LEFTPADDING",   (0, 0), (-1, -1), 8),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 8),
        ("TOPPADDING",    (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(table)
    story.append(Spacer(1, 8 * mm))

    story.append(Paragraph(
        "This sanction is conditional. It will become binding only after an "
        "authorized officer confirms the KYC pack, the risk decision audit log, "
        "and the negotiation history attached to this application. Subject to "
        "RBI V-CIP guidelines.",
        body,
    ))
    story.append(Spacer(1, 10 * mm))
    story.append(Paragraph(
        "— Saarthi Decision Intelligence Engine<br/>"
        "Auto-generated · Reference {ref}<br/>"
        "<i>Not a final loan agreement. Final terms may differ after admin review.</i>".format(ref=ref_no),
        small,
    ))

    doc.build(story)
    return buf.getvalue()
